- app/components/elements/Nav.tsx
- app/routes/about.tsx
first commit :) just seeing everything is ok
> Adds an about page that can be navigated to

- app/components/Headword.tsx
#3 Adds SanitizedTextSpan tag to text. Also added SanitizedTextSpan Tag to generalLabels. See entry `Yankee ((n.))`
I used these words:
toque
la hille
lacaishe
gaspereau
jackash
Yankee ((n.))
> Apply SanitizedTextSpan tag to text

- app/models/entry.server.ts
- app/routes/search.tsx
- app/routes/search/$text.tsx
Enables case sensitivity
So I'm thinking it'd be good to expand the search bar vertically. Just think it looks good.
So right now the IF seems to work pretty well. Not sure if this is viable going forward-- depends on what we need to pass to the query. But I think that's better handled when that problem arises
I recommend using the search parameters "moo" and "MOO" to test the case-sensitive functionality. The words "arctic" and "Arctic" also work
> 7 enable case sensitivity

- app/routes/insertEntry.tsx
A re-do of https://github.com/plot-and-scatter/dchp3/pull/28 to more clearly highlight the exact changes made.
> Improve data insertion css

- app/components/Entry.tsx
- app/components/EntryImages.tsx
closes #35 Adds support for Images in Entry.
> Added images to <Entry/> tag

- app/models/entry.server.ts
- app/routes/search/$text.tsx
closes #17 Enables pagination for search entries
> 17 paginate search entries

- app/routes/entries/browse/$initialLetters/$pageNumber.tsx
Closes #11 Improved button appearance and made minor CSS Adjustments to same file
> improved button appearance

- app/components/SearchResults.tsx
- app/models/entry.server.ts
- app/models/search.server.ts
- app/routes/search.tsx
- app/routes/search/$text.tsx
- app/utils/generalUtils.ts
Adds pagination and searchable meanings
> 45 search meaning

- app/components/Headword.tsx
- app/components/editing/attributeEnum.ts
- app/components/editing/editingPopover.tsx
- app/models/entry.server.ts
- app/routes/entries/$headword.tsx
Closes #49 Adds capacity to edit etymologies and general Labels
> Adds editing functionality for etymology and general lables

- app/components/SearchResults.tsx
Applies sanitized text span to meanings
> Apply sanitize text span to meanings

- app/components/editing/editablePopoverInput.tsx
- app/components/editing/editingPopover.tsx
Adds TextArea support for EditablePopper
> Add TextArea support

- app/components/Headword.tsx
- app/components/elements/Nav.tsx
- app/models/entry.server.ts
- app/models/reference.server.ts
- app/models/update.server.ts
- app/routes/entries/$headword.tsx
- app/routes/reference.tsx
- app/routes/reference/$id.tsx
- app/routes/reference/index.tsx
- app/utils/generalUtils.ts
- app/utils/numberUtils.ts
Adds reference page with Edit functionality. This is practically identical to the one existing in DCHP-2
TODO:
1. implement "add reference" functionality
2. implement "delete reference" functionality
3. improve CSS
> 66 add reference editor page

- app/components/SearchResults.tsx
- app/components/search/SearchResultCanadianism.tsx
- app/components/search/SearchResultFistNotes.tsx
- app/components/search/SearchResultUsageNotes.tsx
- app/models/search.server.ts
- app/routes/search.tsx
- app/routes/search/searchResultEnum.ts
Adds search capacity for `UsageNote`, `FistNote`, and `Canadianism`
closes #80
> 80 enable search for UsageNote, FistNote, Canadianism

- app/components/Meaning.tsx
- app/components/editing/EditingPopover.tsx
- app/components/editing/attributeEnum.ts
- app/components/headwordComponents/Headword.tsx
- app/components/meaningComponents/MeaningHeaderForm.tsx
- app/models/update.server.ts
- app/routes/entries/$headword.tsx
closes #75 closes #55 this makes definitions editable for Entries. Also makes: Order, Usage Note, and Part Of Speech editable for Entries
> 75 makes definition editable

- app/components/Meaning.tsx
- app/components/meaningComponents/MeaningHeaderForm.tsx
- app/models/update.server.ts
- app/routes/entries/$headword.tsx
- app/types/CanadianismTypeEnum.ts
closes #113 adds canadianism type updating
> Makes editing canadianism type possible

- app/components/bank/BankCitationResult.tsx
- app/models/bank.server.ts
- app/models/bank.types.ts
- app/root.tsx
- app/routes/bank.tsx
- app/routes/bank/citations/$headword.tsx
- app/routes/bank/edit/$citationId.tsx
- app/routes/bank/headword-list/$initialLetter.tsx
- app/routes/bank/headword-list/index.tsx
- app/routes/bank/own.tsx
> 136 bank headword list

- app/components/elements/Nav.tsx
- app/components/elements/NavItem.tsx
- app/components/elements/NavPopoverContents.tsx
- app/components/elements/Popover.tsx
- app/routes/bank.tsx
> 148 bank interface tidying

- app/routes/entries/$headword/edit/AddSeeAlso.tsx
- app/routes/entries/$headword/edit/SeeAlsoInput.tsx
closes #149 Adds a build in headword search to the See Also adding input
> 149 see also autofill

- app/components/bank/BankSearchResult.tsx
- app/components/editing/CitationSearch.tsx
- app/routes/admin.tsx
- app/routes/api/citations/$searchTerm[.json].tsx
- app/routes/bank/search/$searchTerm.tsx
- app/routes/playground.tsx
- app/services/bank/searchCitations.ts
> Basic citation search box

- app/components/EntryImage.tsx
- app/components/EntryImages.tsx
- app/models/entry.server.ts
- fly.toml
- prisma/schema.prisma
> Show images properly

- app/components/editing/attributeEnum.ts
- app/models/update.server.ts
- app/routes/entries/$headword/edit.tsx
- app/routes/entries/$headword/edit/MeaningEditingForm.tsx
- app/routes/entries/$headword/edit/MeaningEditingForms.tsx
- app/routes/entries/$headword/edit/QuotationAddingForm.tsx
- app/routes/entries/$headword/edit/QuotationList.tsx
> 165 add bce search to entry editor

- app/components/EntryImage.tsx
- app/routes/entries/$headword/index.tsx
> Fix process.env not being available client-side

- app/components/Entry.tsx
> Remove Images text

- app/components/Entry.tsx
- app/components/EntryReference.tsx
- app/components/EntryReferences.tsx
- app/models/entry.server.ts
- app/models/reference.server.ts
- app/routes/reference/$id.tsx
- prisma/schema.prisma
> Add references to entry

- app/routes/api/citations/$searchTerm[.json].tsx
- app/routes/bank/search/index.tsx
- app/routes/entries/$headword/edit/QuotationAddingForm.tsx
- app/routes/entries/$headword/edit/QuotationList.tsx
- app/services/bank/searchCitations.ts
- app/utils/generalUtils.ts
> 177 bce adding sorted by column

- app/components/SearchResults.tsx
- app/components/elements/DefaultErrorBoundary.tsx
- app/components/search/SearchResultQuotations.tsx
- app/models/search.server.ts
- app/routes/search/$text.tsx
Closes #159 Closes #183 Closes #83 
Adds quotation search and makes error messages display themselves properly
> 159 Add quotation search functionality and fix searching errors

- app/components/SearchResults.tsx
- app/components/search/SearchResultQuotations.tsx
- app/models/search.server.ts
- app/routes/search.tsx
- app/routes/search/$text.tsx
- app/routes/search/searchResultEnum.ts
closes #184 Adds all search functionality.
> 184 add search all option

- app/components/Entry.tsx
- app/components/EntryReference.tsx
- app/components/editing/CitationSearch.tsx
- app/models/entry.server.ts
- app/models/update.server.ts
- app/models/user.server.ts
- app/routes/entries/$headword/edit.tsx
- app/routes/insertEntry.tsx
- app/routes/reference/$id.tsx
- app/services/auth/AuthRole.ts
- app/services/bank/getOwnCitations.ts
- app/services/bank/searchCitations.ts
closes #79 closes #105  Adds a redirect for the user if they don't have editing perms
> 105 edit only with permissions

- app/components/DictionaryVersion.tsx
- app/components/Entry.tsx
- app/components/EntryImages.tsx
- app/components/EntryReference.tsx
- app/components/EntryReferences.tsx
- app/components/HandNoteBlock.tsx
- app/components/Meaning.tsx
- app/components/SanitizedTextSpan.tsx
- app/components/editing/EditingStatus.tsx
- app/components/editing/EditingTools.tsx
- app/components/headwordComponents/Headword.tsx
- app/components/quicklinks/QuickLinks.tsx
- app/models/bank.server.ts
- app/models/entry.server.ts
- app/models/user.server.ts
- app/routes/bank/create.tsx
- app/routes/bank/edit/$citationId.tsx
- app/routes/entries/$headword/edit.tsx
- app/routes/entries/$headword/edit/EntryEditingForm.tsx
- app/routes/entries/$headword/edit/MeaningEditingForm.tsx
- app/routes/entries/$headword/edit/MeaningEditingForms.tsx
- app/routes/entries/$headword/index.tsx
- app/services/auth/auth.server.ts
- app/services/auth/session.server.ts
- app/services/bank/getOwnCitations.ts
- app/styles/additional.css
- app/utils/textUtils.ts
- prisma/schema.prisma
- tsconfig.json
* Fix #172 
* Fix #173 
* Fix #189
* Fix #200
* Fix #201
> Various minor fixes

- app/models/search.server.ts
- app/routes/admin.tsx
- app/routes/reference/addReference.tsx
- app/routes/reference/index.tsx
- app/routes/search.tsx
- app/routes/search/$searchTerm.tsx
- app/services/auth/AuthRole.ts
* Fix #213 
* Fix #214 
* Fix #209
* Fix #217 
* Fix #218
> Various small fixes

- app/components/editing/EditingStatus.tsx
- app/components/editing/EditingTools.tsx
- app/components/editing/EntryComment.tsx
- app/components/editing/attributeEnum.ts
- app/components/editing/entry/EditEntry.tsx
- app/models/update.server.ts
- app/routes/entries/$headword/edit.tsx
> 160 add comment box

- app/components/bank/BankSearchResult.tsx
- app/components/editing/CitationSearch.tsx
- app/routes/api/citations/$searchTerm[.json].tsx
- app/routes/bank/search/$searchTerm.tsx
- app/routes/entries/$headword/edit/QuotationAddingForm.tsx
- app/services/bank/searchCitations.ts
- sql/clean-database.sql
Fix #270.
* Needed to update timestamps to replace `0000-00-00 00:00:00` with `NULL`
*Needed to update the pageNumber parameter
> 270 citation search failing

- app/components/Entry/Headword/Headword.tsx
- app/services/controllers/entry/addImage.ts
- app/services/controllers/entry/updateEditingComment.ts
- app/services/controllers/entry/updateEntry.ts
- app/services/controllers/image/updateImage.ts
> Fix schemas. Fix #338. Fix #347.

- app/services/controllers/ZOptionalStringToEmptyString.ts
- app/services/controllers/entry/addDefinitionFistNote.ts
- app/services/controllers/entry/updateEditingComment.ts
- app/services/controllers/entry/updateEntry.ts
- app/services/controllers/image/updateImage.ts
- app/services/controllers/meaning/addSeeAlso.ts
- app/services/controllers/meaning/updateMeaning.ts
> Coerce optional strings to empty string. Fix #352

- app/components/EntryEditor/EditMeanings/EditFistNotes/FistnoteAddingForm.tsx
- app/components/EntryEditor/EntryEditorForm/MeaningEditorForm.tsx
> Reset fist note form on successful add

- app/components/Entry/Entry.tsx
- app/components/Entry/Meanings/Meaning.tsx
- app/components/Entry/Meanings/Meanings.tsx
- app/components/Entry/Meanings/SeeAlsoItem.tsx
- app/components/Entry/Meanings/SeeAlsoItems.tsx
- app/components/EntryEditor/EditMeanings/EditSees/SeeAlsoInput.tsx
- app/models/entry.server.ts
- app/routes/api/entries/headwords[.json].tsx
- app/routes/entries/$headword/index.tsx
- app/services/controllers/meaning/addSeeAlso.ts
> Allow linking drafts. Fix #359

- app/components/elements/DefaultErrorBoundary.tsx
- app/components/profile/EntryList.tsx
- app/routes/editHistory/$page.tsx
- prisma/schema.prisma
> Fix for deleted entries

- app/models/search/getEntriesByBasicTextSearch.ts
> Search spelling variants. Fix #374

- app/components/EntryEditor/DictionaryVersion.tsx
> Change log entry retrieval method from pop to shift. Fix #376

- app/components/Entry/Meanings/Canadianism.tsx
- app/components/elements/Layouts/TextPageMain.tsx
- app/routes/index.tsx
- app/styles/additional.css
> Add DCHP version

- app/models/search/getSearchResultCanadianisms.ts
- app/models/search/getSearchResultQuotations.ts
- app/models/search/getSearchResultUsageNotes.ts
> Fix Canadianism search
